apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notifications
  name: notifications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications
  template:
    metadata:
      labels:
        app: notifications
    spec:
      containers:
        # - image: notifications:latest #local development image
        #   imagePullPolicy: Never
        - image: europe-west1-docker.pkg.dev/sleepr-464121/notifications/production
          # - image: 135808955271.dkr.ecr.eu-west-3.amazonaws.com/notifications:latest
          name: notifications
          env:
            - name: PORT
              value: '3000'
            - name: GOOGLE_OAUTH_CLIENT_ID
              value: '694149271143-p9n142qe6rm4ko6sji0hmhbqhq05v70l.apps.googleusercontent.com'
            - name: SMTP_USER
              value: 'ericpython1980@gmail.com'
            - name: GOOGLE_OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: google
                  key: clientSecret
            - name: GOOGLE_OAUTH_REFRESH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: google
                  key: refreshToken
          ports:
            - containerPort: 3000
