services:
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    # command: pnpm run start:dev reservations
    command: pnpm run start:debug reservations
    env_file:
      - ./apps/reservations/.env
    ports:
      - '3000:3000'
      - '9229:9229'
    volumes:
      - .:/usr/src/app
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    # command: pnpm run start:dev auth
    command: pnpm run start:debug auth
    env_file:
      - ./apps/auth/.env
    ports:
      - '3001:3001'
      - '9230:9229'
    volumes:
      - .:/usr/src/app
  payments:
    build:
      context: .
      dockerfile: ./apps/payments/Dockerfile
      target: development
    # command: pnpm run start:dev payments
    command: pnpm run start:debug payments
    env_file:
      - ./apps/payments/.env
    ports:
      # - '3003:3003'
      - '9231:9229'
    volumes:
      - .:/usr/src/app
  notifications:
    build:
      context: .
      dockerfile: ./apps/notifications/Dockerfile
      target: development
    # command: pnpm run start:dev notifications
    command: pnpm run start:debug notifications
    env_file:
      - ./apps/notifications/.env
    ports:
      - '9232:9229'
    volumes:
      - .:/usr/src/app
  gateway:
    build:
      context: .
      dockerfile: ./apps/gateway/Dockerfile
      target: development
    # command: pnpm run start:dev gateway
    command: pnpm run start:debug gateway
    env_file:
      - ./apps/gateway/.env
    ports:
      - '3004:3004'
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
