apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auth
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        # - image: auth:latest #local development image
        #   imagePullPolicy: Never
        - image: europe-west1-docker.pkg.dev/sleepr-464121/auth/production
          # - image: 135808955271.dkr.ecr.eu-west-3.amazonaws.com/auth:latest
          name: auth
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: connectionString
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt
                  key: jwtSecret
            - name: JWT_EXPIRATION
              value: '3600'
            - name: TCP_PORT
              value: '3002'
            - name: HTTP_PORT
              value: '3003'
          ports:
            - containerPort: 3002
            - containerPort: 3003
