services:
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    # command: pnpm run start:dev reservations
    command: pnpm run start:debug reservations
    env_file:
      - ./apps/reservations/.env
    ports:
      - '3000:3000'
      - '9229:9229'
    volumes:
      - .:/usr/src/app
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    # command: pnpm run start:dev auth
    command: pnpm run start:debug auth
    env_file:
      - ./apps/auth/.env
    ports:
      - '3001:3001'
      - '9230:9229'
    volumes:
      - .:/usr/src/app
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
