### Create a new user
POST http://192.168.1.30:3001/users/
Content-Type: application/json

{
    "email": "abc2@exa2mple.com",
    "password": "PasswordEcr2025!a@"
}

###Login with the user
POST http://192.168.1.30:3001/auth/login
Content-Type: application/json

{
    "email": "abc2@exa2mple.com",
    "password": "PasswordEcr2025!a@"
}

### Get all reservations
GET http://192.168.1.30:3000/reservations

### Create a new reservation
POST http://192.168.1.30:3000/reservations
Content-Type: application/json

{
  "startDate": "02-01-2025",
  "endDate": "02-05-2025",
  "placeId": "123",
  "invoiceId": "123",
  "charge": {
    "amount": 20.03,
    "card": {
      "token": "tok_mastercard_debit"
    }
  }
}


### Create a new user - NOTIFICATIONS
POST http://192.168.1.30:3001/users/
Content-Type: application/json

{
    "email": "eric.carlier@gmail.com",
    "password": "PasswordEcr2025!a@"
}

###Login with the user
POST http://192.168.1.30:3001/auth/login
Content-Type: application/json

{
    "email": "eric.carlier@gmail.com",
    "password": "PasswordEcr2025!a@"
}